package fergoman123.mods.fergoutil.lib;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class ModInfo {
    public static final boolean autoGenerated = false;
    public static final String modid = "FergoUtil";
    public static final String name = "Fergoman123's Util";
    public static final String versionMain = "1.7.2-1.0";
    public static final String version = "@version@";
    public static final String logoFile = "/assets/fergoutil/logo.png";
    public static final String author = "Fergoman123";
    public static final String url = "fergoman123.github.io";
    public static final String desc = "Fergoman123's Util is a utility mod thats is used to register items, block and other things";


    public static void writeMetadata(ModMetadata metadata)
    {
        metadata.autogenerated = autoGenerated;
        metadata.modId = modid;
        metadata.name = name;
        metadata.version = versionMain;
        metadata.logoFile = logoFile;
        metadata.authorList = Arrays.asList(author);
        metadata.url = url;
        metadata.description = desc;
    }


}
